### ISSUE TITLE
undefined symbol: wiringPiSetup

### ISSUE THREAD

**Issue by jdrucey** [wertyzp/WiringNP#1]
My apologies if I am asking this in the wrong place, but i have reached a complete dead end!

I am using a library called [node-rcswitch](https://github.com/marvinroger/node-rcswitch) which is reliant on WiringPi.

I am running my project off of a NanoPi NEO so have installed WiringNP as a replacement for WiringPi. node-rcswitch uses the `-lwiringPi` flag when compiling and does so without error.

However, when i come to use it at run time i get the following error: `undefined symbol: wiringPiSetup`

Am i missing something with regards to WiringNP? As far as i understand it, WiringNP can be used in exactly the same way as WiringPi. I just can't figure out why its not working at runtime. =(

**Comment by wertyzp** [comment]
You can check examples/gpio makefiles to see how to add libraries / define compiler options for proper compilation. Please let me know if it helps

**Comment by jdrucey** [comment]
Unfortunately that doesn't help. Like i said, the program is compiled with the `-lwiringPi` flag,  and i have even tried with all the flags listed in the examples here. The script calls the `wiringPiSetup` function at the beginning. Yet i still get that error =(

**Comment by wertyzp** [comment]
can't reproduce
