### ISSUE TITLE
There is mapping bug

### ISSUE THREAD

**Issue by nopnop2002** [wertyzp/WiringNP#4]
Thank you for usefull library.

static int pinToGpio [64] ={
    0, 6, // 0, 1
    2, 3, // 2, 3
    200, 201, // 4  5
    1, 203, // 6, 7
    12, 11, // 8, 9
    67, 17, //10,11
    64, 65, //12,13
    66, 198, //14,15
    199, -1, //16,17
    -1, -1, //18,19
    -1, 20, //20,21
    21, 8, //22,23
//    13, 9, //24,25
    16, 9, //24,25 // Update nopnop2002
//    7, 16, //26,27
    7, 13, //26,27 // Update nopnop2002
    15, 14, //28,29
    19, 18, //30,31

static int pinTobcm [64] ={
    19, 18, //map to BCM GPIO0,1
    12, 11, //map to BCM GPIO2,3
    203, 20, //map to BCM GPIO4,5
    21, 17, //map to BCM GPIO6,7
    67, 65, //map to BCM GPIO8,9
    64, 66, //map to BCM GPIO10,11
    7, 8, //map to BCM GPIO12,13
    198, 199, //map to BCM GPIO14,15
//    16, 0, //map to BCM GPIO16,17
    13, 0, //map to BCM GPIO16,17 // Update nopnop2002
//    6, 13, //map to BCM GPIO18,19
    6, 16, //map to BCM GPIO18,19 // Update nopnop2002
    15, 14, //map to BCM GPIO20,21
    3, 200, //map to BCM GPIO22,23
    201, 1, //map to BCM GPIO24,25
//    9, 13, //map to BCM GPIO26,27
    9, 2, //map to BCM GPIO26,27// Update nopnop2002

**Comment by wertyzp** [comment]
thanks for your effort, I will update this shortly

**Comment by wertyzp** [comment]
Please check latest commit and let me know if issue is solved

**Comment by nopnop2002** [comment]
I tested.
It solved.
Please close this issues.
