### ISSUE TITLE
Adaptation for NanoPC T2

### ISSUE THREAD

**Issue by lisandroz** [wertyzp/WiringNP#5]
Hello, I would like to know if there is any kind of implementation for the WiringNP library for the NanoPC T2 board, If not, I would like to know what types of changes I have to make in the mapping to make this work.
I would also like to know the performance of the library in Khz or Mhz. (The basic test setup was toggle one of the GPIO pins between zero and one as fast as possible)
Best Regards

**Comment by wertyzp** [comment]
It is based on cortex a9, this means that it is incompatible with current wiringnp implementation
Try to google wiringpi variant for this cpu and contact authors
